name: Parallel Test Build

on:
  schedule:
    - cron: "20 0 * * *"  # Runs every day at 9:00 PM UTC
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  push:
    branches: [main]

jobs:
  cypress-parallel-e2e:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        
      - name: Cypress run
        uses: cypress-io/github-action@v6.6.1

      - name: Run Parallel Cypress Tests
        run: npm run cy:parallel
      
      - name: Merge Mochawesome Reports
        run: npm run merge:reports

      - name: Generate HTML Report
        run: npm run generate:report

      - name: Upload HTML Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-html
          path: reports/html/
